/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#05070a',
        surface: '#111417',
        'surface-dim': '#111417',
        'surface-bright': '#37393d',
        'surface-container-lowest': '#0c0e12',
        'surface-container-low': '#191c1f',
        'surface-container': '#1d2023',
        'surface-container-high': '#282a2e',
        'surface-container-highest': '#323539',
        'surface-variant': '#323539',
        'on-surface': '#e1e2e7',
        'on-surface-variant': '#c2c6d6',
        outline: '#8c909f',
        'outline-variant': '#424754',
        'surface-tint': '#adc6ff',
        primary: '#adc6ff',
        'on-primary': '#002e6a',
        'primary-container': '#4d8eff',
        'on-primary-container': '#00285d',
        secondary: '#d0bcff',
        'on-secondary': '#3c0091',
        'secondary-container': '#571bc1',
        tertiary: '#4cd7f6',
        'on-tertiary': '#003640',
        'tertiary-container': '#009eb9',
        'on-tertiary-container': '#002f38',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'inverse-primary': '#005ac2',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
      spacing: {
        xs: '8px',
        sm: '16px',
        md: '24px',
        lg: '40px',
        xl: '80px',
        gutter: '24px',
        margin: '32px',
      },
      fontFamily: {
        'body-lg': ['Inter', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'headline-sm': ['Inter', 'system-ui', 'sans-serif'],
        'display-lg': ['Inter', 'system-ui', 'sans-serif'],
        'mono-label': ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
        'headline-md': ['Inter', 'system-ui', 'sans-serif'],
        'mono-data': ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'mono-label': ['12px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '-0.02em', fontWeight: '600' }],
        'mono-data': ['13px', { lineHeight: '1.4', fontWeight: '400' }],
      },
      keyframes: {
        rotateGlow: { '100%': { transform: 'rotate(360deg)' } },
        waveform: { '0%,100%': { height: '8px', opacity: '0.5' }, '50%': { height: '32px', opacity: '1' } },
        scanline: { '0%': { transform: 'translateY(-100%)' }, '100%': { transform: 'translateY(100vh)' } },
        scanlineFast: { '0%': { transform: 'translateX(-100%)' }, '100%': { transform: 'translateX(100%)' } },
        pulseGlow: { '0%,100%': { boxShadow: '0 0 10px 0 rgba(76,215,246,0.2)' }, '50%': { boxShadow: '0 0 30px 5px rgba(76,215,246,0.6)' } },
      },
      animation: {
        rotateGlow: 'rotateGlow 4s linear infinite',
        waveform: 'waveform 1s ease-in-out infinite',
        scanline: 'scanline 4s linear infinite',
        scanlineFast: 'scanlineFast 2s linear infinite',
        pulseGlow: 'pulseGlow 2s cubic-bezier(0.4,0,0.6,1) infinite',
      },
    },
  },
  plugins: [],
};
